bst_plugin/nst_get_repository_url.m, bst_plugin/nst_request_files.m, run_tests.m, test/utest_clean_bst.m, test/utest_import_nirs_in_bst.m, test/utest_reset_bst.m
Switch to more stable URL for default data repository. Fix when test suite is empty. Improve handling of temporary protocol creation during unit tests.
=> Minor fixes and improvements of installation and unit testing

bst_plugin/MANIFEST, bst_plugin/nst_add_scout_sel_options.m, bst_plugin/nst_get_option_selected_scout.m, bst_plugin/process_nst_cpt_fluences_from_cortex.m, bst_plugin/process_nst_cpt_fluences_from_head.m
Add computation of fluences from MRI and 5 tissue segmentation (call MCXlab). Add lister of user-defined scouts to select cortical ROI.
=> computation of fluences via MCXlab

bst_plugin/nst_add_scout_sel_options.m, bst_plugin/nst_get_option_selected_scout.m, bst_plugin/nst_request_files.m, bst_plugin/process_nst_OM_from_head.m, bst_plugin/process_nst_import_head_model.m, test/OptimalMontageTest.m, test/bst_create_scout.m, test/bst_create_test_subject.m, test/cpt_spherical_fluences.m, test/utest_bst_setup.m
Gain around 30x computation time and around 10x memory usage.
Now a large OM can be computed in less than 10 min while consuming less than 1Gb of RAM.
=> Optimal montage optimization

bst_plugin/VERSION, dist_tools/install_package.m, run_tests.m, test/InstallSourceTest.m
Add more tests for matlab version handling
=> test matlab version handling

bst_plugin/nst_add_scout_sel_options.m, bst_plugin/process_nst_get_data_perform_2018.m, test/WorkShopPerform2018Test.m
Finished reviewing the setup process and main tutorials.
[Wiki page](https://github.com/Nirstorm/nirstorm/wiki/Workshop-PERFORM-Week-2018) has been updated.
=> Workshop perform 2018

bst_plugin/MANIFEST.wip, bst_plugin/process_nst_compute_glm.m
Improve subgroup name (NIRS - wip). Set tutorial link to github wiki page.
Add process to MANIFEST.wip. -> Use `nst_install('link', {'debug', 'wip'})`
=> [GLM] minor fixes

bst_plugin/MANIFEST.wip, bst_plugin/process_nst_compute_glm.m, bst_plugin/process_nst_compute_ttest.m
HI. 
This is the first implementation of the ttest that work on the channel space. The input is in the SPM format( [-1 1] ) as we have discussed.
I've changed a litle bit the process that compute the glm so that we have access to the covariance matrix and the associated degree of freedom. ( The wiki page is up-to-date) 
It is functional but there is still one issue with visualisation that I was not able to solve ;
The pmap can only be display in brainstorm as a 3D sensor cap and not as 3D optodes. 
Best, 
Edouard
=> [GLM]  Ttest implementation

bst_plugin/MANIFEST, bst_plugin/MANIFEST.wip, bst_plugin/nst_channel_types.m, bst_plugin/nst_format_channel.m, bst_plugin/nst_get_pair_indexes_from_names.m, bst_plugin/nst_unformat_channel.m, bst_plugin/nst_unformat_channels.m, bst_plugin/process_nst_detect_bad.m, bst_plugin/process_nst_motion_correction.m, bst_plugin/process_nst_sci.m, test/MontageTest.m, test/SciTest.m
Implementation of the Scalp Coupling Index (cross-correlation between wavelengths).
Unit tests on simulations and real data (non-regression).
Documentation is done on the [wiki](https://github.com/Nirstorm/nirstorm/wiki/Scalp-coupling-index)
=> [Quality check] Scalp coupling index

bst_plugin/process_nst_compute_glm.m
Add selection of stimulation events instead of taking all events. Add sanity checks on events. Ignore non-NIRS channels. Add ouputs of beta maps.
=> Improvement of GLM

bst_plugin/process_nst_compute_ttest.m
Add the semantic contrast definition and some test on the inputs
=> Ttest improvement

bst_plugin/process_nst_compute_group_ttest.m
The PR is not ready to be merge as I need to implement some test on the inputs to make sure that all files are consistent but can you give me an overall review of this process ?
=> Group level

bst_plugin/process_nst_import_evt_events.m
Add a button that list the events that are going to be imported.
=> Evt improvement

bst_plugin/process_nst_mbll.m, test/MbllTest.m
Fix bug log10 instead of log in OD computation. Improve unit testing.
Results on motor data for non-regression utest has been update in repo.
=> Fix scaling bug

bst_plugin/process_nst_import_evt_events.m, bst_plugin/process_nst_import_head_model.m, bst_plugin/process_nst_separations.m
- Clean up process parameters.
- Add link to wiki doc
- Optimize memory a bit (fluence volumes). 
- Fix fluence normalization when ref is null (was oustide of mask) but separation is not large (below 5.5cm). Use the minimum fluence value as reference in this case. Add proper warning if it happens.
=> Improve head model

bst_plugin/MANIFEST, bst_plugin/nst_knnsearch.m, bst_plugin/nst_request_files.m, bst_plugin/process_nst_OM_from_head.m, bst_plugin/process_nst_cmem.m, bst_plugin/process_nst_cpt_fluences_from_cortex.m, bst_plugin/process_nst_import_head_model.m, bst_plugin/process_nst_wmne.m, dist_tools/check_dependencies.py
- add alternate code for knnsearch
- add proper error when stats toolbox is not available
=> Improve dependencies

bst_plugin/process_nst_compute_voronoi.m, bst_plugin/process_nst_cortical_projection_mne.m, bst_plugin/process_nst_import_head_model.m
- fix bug in reading segmentation in Voronoi
- Add sensitivity thresholding
- Fix handling of link to raw data
=> Fix projection

bst_plugin/MANIFEST, bst_plugin/nst_bst_add_surf_data.m, bst_plugin/nst_make_event_regressors.m, bst_plugin/nst_make_event_toeplitz_mtx.m, bst_plugin/process_nst_compute_glm.m, bst_plugin/process_nst_import_head_model.m, test/GLMTest.m, test/bst_create_test_subject.m, test/utest_import_nirs_in_bst.m
- clean up creation of design matrix
- starts unit test on simulated cortical data
- switch to [low resolution Colin27 template](http://thomasvincent.xyz/nst_data/template/Colin27_4NIRS_lowres.zip)
=> Surface glm

bst_plugin/process_nst_compute_glm.m
=> minor fixes

bst_plugin/MANIFEST, bst_plugin/nst_filter_table.m, test/FilterTableTest.m
Add helper function to filter table. To be used to sort out data sets to process.
=> Data management

bst_plugin/MANIFEST, bst_plugin/process_nst_separations.m, test/BstHelperTest.m, test/GLMTest.m
Fix some utests and missing files
=> Fix for release

bst_plugin/process_nst_wmne.m
-add a progress bar when solving MNE
-fix some typo
=> Minor change in wMNE process

bst_plugin/process_nst_iir_filter.m
* Make the output more consistent with a brainstorm and compute the transient effect of the filter
* Allow changing the order of the filter (maybe to remove as the filter can become unstable ? )
* Add previsualization
=> Filtering improvement

bst_plugin/process_nst_glm_fit.m
* fix crash if no file input as file B
* fix crash if no high-pass filter used
=> small GLM fix

bst_plugin/MANIFEST, bst_plugin/process_nst_OM_from_cap.m, bst_plugin/process_nst_OM_from_cortex.m, bst_plugin/process_nst_OM_from_head.m, bst_plugin/process_nst_import_evt_events.m, bst_plugin/process_nst_import_head_model.m
Add a process to compute OM from a pre-defined cap. 
From top to bottom: the original cap based on the 10-5 system, the NIRS montage and the montage with EEG name.
Channel files that contain all the information for the montage.
=> OM from a pre-defined cap. 

bst_plugin/GLM/nst_glm_add_regressors.m, bst_plugin/GLM/nst_glm_apply_filter.m, bst_plugin/GLM/nst_glm_display_model.m, bst_plugin/GLM/nst_glm_fit.m, bst_plugin/GLM/nst_glm_fit_B.m, bst_plugin/GLM/nst_glm_initialize_model.m, bst_plugin/GLM/process_nst_glm_fit.m, bst_plugin/MANIFEST, bst_plugin/MANIFEST.wip, bst_plugin/math/nst_math_build_basis_dct.m, bst_plugin/math/nst_math_dctmtx.m, bst_plugin/misc/nst_misc_convert_to_mumol.m, bst_plugin/misc/nst_misc_unpack_glm_result.m, bst_plugin/preprocessing/process_nst_detrend.m, bst_plugin/preprocessing/process_nst_extract_ssc.m, bst_plugin/preprocessing/process_nst_iir_filter.m, bst_plugin/preprocessing/process_nst_remove_ssc.m
Implementation of #129 
close #117 
close #129
=> GLM updates

bst_plugin/GLM/nst_glm_apply_filter.m, bst_plugin/GLM/process_nst_glm_fit.m, bst_plugin/preprocessing/process_nst_detrend.m, bst_plugin/preprocessing/process_nst_remove_ssc.m
string using "" have been introduced with matlab2017a
=> GLM - fix compatibility with matlab 2016

bst_plugin/mbll/process_nst_dOD.m, bst_plugin/mbll/process_nst_mbll.m
=> Check for negative values in process_nst_mbll.m is done on NIRS and AUX data

bst_plugin/MANIFEST, bst_plugin/mbll/process_nst_dOD.m, bst_plugin/mbll/process_nst_mbll.m, bst_plugin/mbll/process_nst_mbll_dOD.m
- dOD: save signal under a new condition, and keep good auxilary signals 
- MBLL: add a process to compute concentration from dOD
=> dOD and MBLL update

bst_plugin/MANIFEST, bst_plugin/math/nst_spline_correction.m, bst_plugin/math/nst_tddr_correction.m, bst_plugin/preprocessing/process_nst_motion_correction.m
- Add the possibility to choose the smoothing parameters for motion correction using spline
- Add the Temporal Derivative Distribution Repair motion correction algorithm
- Add citation
=> Motion correction update

bst_plugin/GLM/process_nst_combine_masks.m, bst_plugin/GLM/process_nst_extract_fov_mask_cortical.m, bst_plugin/GLM/process_nst_glm_group_subjs_zmat.m, bst_plugin/GLM/process_nst_spree.m, bst_plugin/inverse/process_nst_cmem_fusion.m, bst_plugin/inverse/process_nst_cortical_projection.m, bst_plugin/io/process_nst_concat_matrices.m, bst_plugin/io/process_nst_convert_to_stat.m, bst_plugin/io/process_nst_import_csv_events.m, bst_plugin/io/process_nst_import_evt_events.m, bst_plugin/io/process_nst_import_nirs_as_tstat.m, bst_plugin/io/process_nst_prefix_matrix.m, bst_plugin/io/process_nst_save_matrix_csv.m, bst_plugin/mbll/process_nst_dOD_SSR.m, bst_plugin/mbll/process_nst_mbll_SSR.m, bst_plugin/preprocessing/process_nst_detect_bad_CV.m, bst_plugin/preprocessing/process_nst_surfacedepth.m, dist_tools/install_package.m, nst_install.m, nst_uninstall.m, updates.txt
Based on Francois 's comment :
*  process should be moved to .brainstorm/process
* function to  .brainstorm/nirstorm
* mex to .brainstorm/mex
=> Fix installation script

bst_plugin/GLM/nst_glm_add_regressors.m, bst_plugin/GLM/process_nst_glm_fit.m, bst_plugin/VERSION, bst_plugin/preprocessing/process_nst_remove_ssc.m, updates.txt
Short Separation channel regression - Uses the mean of the short separation channels as regressors
=> Update short-separation channel process

bst_plugin/OM/process_nst_OM.m
=> Revert "Fix Cplex version issue"

bst_plugin/preprocessing/process_nst_remove_ssc.m
For backward compatibility with previous Matlab versions
=> Replace double quotes with single quotes

bst_plugin/GLM/nst_glm_add_regressors.m, bst_plugin/GLM/nst_glm_fit.m, bst_plugin/GLM/process_nst_glm_fit.m
Also, normalize signal to use as regressors
=> [Bugfix] Uses correct chromophores for SS regression

bst_plugin/forward/process_nst_compute_voronoi.m
Slight improvement in saving time by removing one call to in_mri_bst 
see https://github.com/Nirstorm/nirstorm/issues/224
=> improve voronoi saving performance

bst_plugin/forward/process_nst_cpt_cortex_to_head_distance.m, bst_plugin/forward/process_nst_extract_sensitivity_from_head_model.m
For each point of the cortex, return the distance to the closest point on the head. This corresponds to the depth of the vertex. Deep structures will have a larger value.
=> add process to compute distance from cortex to head

bst_plugin/GLM/process_nst_glm_fit.m
=> [GLM] improve file loading

bst_plugin/forward/process_nst_import_head_model.m
Head model importation was bloated with several options not recommended to the user. This simplifies the interface a lot to only keep what is necessary
=> [ENH] Simplify head model importation

bst_plugin/preprocessing/process_nst_detect_bad.m
See https://neuroimage.usc.edu/forums/t/nirstorm-qt-nirs-detect-bad-channels-does-not-work/48658
=> fix the bad channel detection using QT

bst_plugin/preprocessing/process_nst_detect_bad.m
This option was not recommended.
=> [detect bad channels] Remove the option to keep unpaired channels

bst_plugin/OM/process_nst_OM.m
Fix a small bug when multiple atlas are present in the head surface
=> [OM[ Fix atlas selection 

bst_plugin/preprocessing/process_nst_quality_check.m
- Only report quality checks for good channels
- Improve backward compatibility 
- Fix units (cm vs mm)
=> improve quality check

bst_plugin/core/nst_montage_info_from_bst_channels.m, bst_plugin/inverse/process_nst_cmem.m, bst_plugin/inverse/process_nst_wmne.m, bst_plugin/math/nst_mbll_source.m, bst_plugin/misc/nst_misc_FOV_to_cortex.m
Some refactoring of the code for MNE and MEM: 
- avoid some code duplication
- support the source reconstruction when only one wavelength is available (useful for simulation)
- remove the use of the function add_surf_data ( i dont like that function)
=> [refactor] Improve file saving for MNE and MEM

bst_plugin/inverse/process_nst_cmem.m
Remove the option to estimate the NBO automatically as it tends to suggest a high value. 
Todo list:
=> Remove the option to compute the NBO automatically

bst_plugin/inverse/process_nst_cmem.m
followup on the previous commit
=> [cMEM] fix removal of NBO

bst_plugin/OM/panel_nst_OM.m, bst_plugin/VERSION, bst_plugin/forward/panel_nst_fluences.m
- Remember options
- Automatically load mxclab
=> [refactor] improve panel for fluence computation

bst_plugin/VERSION, bst_plugin/preprocessing/process_nst_detect_bad.m, bst_plugin/preprocessing/process_nst_quality_check.m, bst_plugin/preprocessing/process_nst_separations.m
For raw data, save the quality check in their own folder as raw data needs to be alone in their folder
=> Quality check - save data in their own folder for raw input data

bst_plugin/OM/process_nst_OM.m, bst_plugin/VERSION
- Improve cplex check and give the user the possibility to give the path to cplex if it is not found
- Fix the bug if the weight cache was outdated
- Always open the bst report at the end of the process
=> [Bug fix] Improve optimal montage

README.md, bst_plugin/preprocessing/process_nst_detect_bad.m
This PR: 
- fix a bug when applied to concentration 
- improve the repporting of the new bad channels
=> [bugfix] improve bad channel detection for concentration
